// Delvers, enemies and bosses. 16 x 16 unless noted; bosses are 32 x 32, drawn as a left half.
(function (A) {
  'use strict';

  A.group('delvers', 'Delvers', 'Four class looks on one body plan. C and c are the cloak and its shade, so any class takes any cloak. Only the lamplighter is in the slice; class design is still open (SPEC §4).');
  A.group('enemies', 'Enemies', 'Sixteen-pixel creatures. Symmetric ones are drawn as a left half and mirrored.');
  A.group('bosses', 'Bosses', 'Thirty-two pixels square, each drawn as a sixteen-column half. One per dungeon.');

  const CLOAKS = { 'Verdigris cloak': { C: 't', c: 'd' }, 'Ember cloak': { C: 'e', c: 'R' }, 'Bone cloak': { C: 'b', c: 'n' }, 'Shade cloak': { C: 'P', c: 'p' } };
  const cloaksBut = function (skip) { const o = {}; for (const k in CLOAKS) if (k !== skip) o[k] = CLOAKS[k]; return o; };

  /* ---------- delvers ---------- */
  A.add('delvers', 'lamplighter', { name: 'Lamplighter', slice: true, walk: true, map: CLOAKS['Verdigris cloak'], variants: cloaksBut('Verdigris cloak'), rows: [
    '................',
    '....kkkkkk......',
    '..kkCCCCCCkk....',
    '.kCCCCCCCCCCk...',
    '.kCCkkkkkkCCk...',
    '.kCkSSSSSSkCk...',
    '.kCkSkSSkSkCk...',
    '.kckSSSSSSkck.k.',
    '..kkkSSSSkkk.kkk',
    '.kCCCkkkkCCCkyYk',
    'kCCcCCCCCCcCSyyk',
    'kCccCCCCCCcckkk.',
    'kCccCCCCCCcck...',
    '.kccCCkkCCcck...',
    '..kwwk..kwwk....',
    '..kkkk..kkkk....'] });
  A.add('delvers', 'reeve', { name: 'Reeve', walk: true, map: CLOAKS['Ember cloak'], variants: cloaksBut('Ember cloak'), rows: [
    '................',
    '....kkkkkk......',
    '..kkmmMMmmkk....',
    '.kmmMMMMMMmmk.k.',
    '.kmmkkkkkkmmkkMk',
    '.kmkSSSSSSkmkkMk',
    '.kmkSkSSkSkmkkMk',
    '.kikSSSSSSkikkMk',
    '..kkkSSSSkkk.kMk',
    '.kCCCkkkkCCCkkMk',
    'kCCcCCCCCCcCSgGg',
    'kCccCCCCCCcckkgk',
    'kCccCCCCCCcck.k.',
    '.kccCCkkCCcck...',
    '..kwwk..kwwk....',
    '..kkkk..kkkk....'] });
  A.add('delvers', 'fletcher', { name: 'Fletcher', walk: true, map: { C: 'h', c: 'd' }, variants: CLOAKS, rows: [
    '................',
    '....kkkkkk......',
    '..kkCCCCCCkk....',
    '.kCCCCCCCCCCk.W.',
    '.kCCkkkkkkCCk6.W',
    '.kCkSSSSSSkCk6.W',
    '.kCkSkSSkSkCk6.W',
    '.kckSSSSSSkck6.W',
    '..kkkSSSSkkk.6.W',
    '.kCCCkkkkCCCk6.W',
    'kCCcCCCCCCcCSSSW',
    'kCccCCCCCCcck6.W',
    'kCccCCCCCCcck6W.',
    '.kccCCkkCCcckW..',
    '..kwwk..kwwk....',
    '..kkkk..kkkk....'] });
  A.add('delvers', 'chirurgeon', { name: 'Chirurgeon', walk: true, map: { C: '4', c: '3' }, variants: CLOAKS, rows: [
    '................',
    '..kkkkkkkkkk....',
    '..k22222222k....',
    'kkkkkkkkkkkkkk..',
    '.kCkBBBBBBkCk...',
    '.kCkkkBBkkkCk...',
    '.kCkTkBBkTkCk...',
    '.kckBBBBBBkck.k.',
    '..kkkBnnBkkk.kkk',
    '.kCCCknnkCCCkyYk',
    'kCCcCCkkCCcCSyyk',
    'kCccCCCCCCcckkk.',
    'kCccCeCCCCcck...',
    '.kccCCkkCCcck...',
    '..kwwk..kwwk....',
    '..kkkk..kkkk....'] });

  /* ---------- enemies ---------- */
  A.add('enemies', 'forgotten', { name: 'The Forgotten', slice: true, variants: { 'Charred': { B: '5', b: '4', e: 'o' } }, rows: [
    '................',
    '.....kkkkkk.....',
    '....kBBBBBBk....',
    '...kBBBBBBBBk...',
    '...kBkkBBkkBk...',
    '...kBkeBBekBk...',
    '...kBBBkkBBBk...',
    '....kBBBBBBk....',
    '....kbkbkbkk....',
    '..kk.kkbbkk.kk..',
    '.kbbkkbBBbkkbbk.',
    '.kbk.kbkkbk.kbk.',
    '.kbk.kbBBbk.kbk.',
    '.kik..kbbk..kik.',
    '..k..kbkkbk..k..',
    '.....kkk.kkk....'] });
  A.add('enemies', 'bone_archer', { name: 'Bone Archer', rows: [
    '................',
    '.....kkkkkk.....',
    '....khhhhhhk....',
    '...khhhhhhhhk...',
    '...khkkBBkkhkW..',
    '...kBkeBBekBk6W.',
    '...kBBBkkBBBk6.W',
    '....kBBBBBBk.6.W',
    '....kbkbkbkk.6.W',
    '..kk.kkbbkk.kkkW',
    '.kbbkkbBBbkkbbbW',
    '.kbk.kbkkbk.kk6W',
    '.kbk.kbBBbk..6W.',
    '.kik..kbbk...W..',
    '..k..kbkkbk.....',
    '.....kkk.kkk....'] });
  A.add('enemies', 'shade', { name: 'Shade', slice: true, variants: { 'Cinder': { P: 'o', p: 'r' }, 'Marsh light': { P: 'T', p: 't' } }, rows: [
    '................',
    '.......kk.......',
    '......kPPk......',
    '......kP#Pk.....',
    '.....kPP#PPk....',
    '....kPPP##PPk...',
    '...kPP#####PPk..',
    '...kP##k##k#Pk..',
    '...kP##k##k#Pk..',
    '...kPP#####PPk..',
    '...kpPP#k#PPpk..',
    '....kpPPPPPpk...',
    '.....kppPppk....',
    '......kkpkk.....',
    '........k.......',
    '................'] });
  A.add('enemies', 'gaoler', { name: 'Gaoler', slice: true, variants: { 'Gaol captain': { R: 'd', e: 't', m: 'g', M: 'G', i: 'w' } }, rows: [
    '....kkkkkkkk....',
    '...kiiiiiiiik...',
    '..kimmmmmmmmik..',
    '..kimMMmmMMmik..',
    '..kikkkmmkkkik..',
    '..kikeekkeekik..',
    '..kimmmkkmmmik..',
    '..kkimmmmmmikk..',
    '.kRRkkkkkkkkRRk.',
    'kRRRRkwwwwkRRRRk',
    'kRReRkwGGwkReRRk',
    'kSkRRkwwwwkRRkSk',
    'kkkRRRRRRRRRRkkk',
    '..kRRRkkkkRRRk..',
    '..kiik....kiik..',
    '..kkkk....kkkk..'] });
  A.add('enemies', 'rat', { name: 'Gutter Rat', variants: { 'Plague rat': { '5': 'h', '4': 'd', e: 'y' } }, rows: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..........kk.kk.',
    '.........k4ksk4k',
    '....kkkkkk4444k.',
    '..kk555555444e4k',
    '.k555555554444sk',
    'sk555455554444k.',
    's.k5k44k5k44kk..',
    '.s.kk..kk.kk....',
    '..ss............'] });
  A.add('enemies', 'hound', { name: 'Gaol Hound', variants: { 'Ash hound': { R: '4', e: '6' } }, rows: [
    '................',
    '................',
    '................',
    '................',
    '...........k..k.',
    '..........kRkkRk',
    '..........kRRRRk',
    '.k........kRyRRk',
    'kRk..kkkkkRRRR#k',
    '.kRkkReeeeRRRkk.',
    '..kRRRRRRRRRRk..',
    '..kRRRRRRRRRk...',
    '..kRRkkkkkRRk...',
    '..kRk.....kRk...',
    '..kRk.....kRk...',
    '..kkk.....kkk...'] });
  A.add('enemies', 'bat', { name: 'Gaol Bat', variants: { 'Ember bat': { p: 'r', v: 'R', e: 'y' } }, half: [
    '........',
    '........',
    '........',
    '.kk...kk',
    'kvvk.kpk',
    'kvvvkkpp',
    'kvvvvpep',
    'kvvkvppp',
    '.kk.kvp#',
    '....kvpp',
    '.....kkp',
    '.......k',
    '........',
    '........',
    '........',
    '........'] });
  A.add('enemies', 'ooze', { name: 'Gutter Ooze', variants: { 'Cistern ooze': { H: 'T', h: 't' }, 'Slag': { H: 'o', h: 'r', '#': 'Y' } }, half: [
    '........',
    '........',
    '........',
    '........',
    '......kk',
    '....kkHH',
    '...kHHHH',
    '..kHH#HH',
    '..kHHHHH',
    '.kHHkkHH',
    '.kHhkkHH',
    '.khHHHHH',
    'khhHHHhh',
    'khhhhhhh',
    '.kkkkkkk',
    '........'] });
  A.add('enemies', 'spider', { name: 'Cell Spider', variants: { 'Pale spider': { p: 'b', '4': 'n', e: 'e' } }, half: [
    '........',
    '........',
    '........',
    '4.......',
    '.4..4...',
    '..4..4..',
    '...4.kkk',
    '44..kkpp',
    '..44kppp',
    '...kppep',
    '4444pppp',
    '...kkpp#',
    '..4..kkk',
    '.4..4...',
    '4...4...',
    '........'] });
  A.add('enemies', 'mould', { name: 'Redcap Mould', variants: { 'Gloomcap': { e: 'p', '#': 'P' }, 'Rotcap': { e: 'h', '#': 'H' } }, half: [
    '........',
    '........',
    '....kkkk',
    '..kkeeee',
    '.keee#ee',
    'kee#eeee',
    'keeeeee#',
    'kkeeeeee',
    '..kkkkkk',
    '...kbbbb',
    '...kbkbb',
    '...kbbbb',
    '...kbbnn',
    '..kbbbnn',
    '..kkkkkk',
    '........'] });
  A.add('enemies', 'imp', { name: 'Cinder Imp', variants: { 'Shade imp': { o: 'P', r: 'p', y: '#' } }, half: [
    '........',
    'k.......',
    'kk...kkk',
    '.kkkkooo',
    '..kooooo',
    '..koykoo',
    '..kooooo',
    '..kkorro',
    '.kkkkooo',
    'koo.kooo',
    'ko..kooo',
    'k...krro',
    '....kook',
    '...kok.k',
    '...kk...',
    '........'] });
  A.add('enemies', 'drowned', { name: 'The Drowned', variants: { 'Bog-pale': { t: 'n', T: 'b', d: '5' } }, half: [
    '........',
    '....kkkk',
    '...ktttt',
    '..kttTTT',
    '..ktkktT',
    '..ktk#tT',
    '..kttttt',
    '...kttkk',
    '..kkdttt',
    '.kttkddt',
    'kttkkdtt',
    'ktk.kdtt',
    'khk.kdtd',
    '.k..ktdk',
    '...kttk.',
    '...kkkk.'] });
  A.add('enemies', 'wraith', { name: 'Chained Wraith', variants: { 'Drowned wraith': { '5': 't', '6': 'T', T: '#' } }, half: [
    '........',
    '....kkkk',
    '...k5555',
    '..k55666',
    '..k56kkk',
    '..k56kTk',
    '..k56kkk',
    '.k556666',
    '.k556556',
    'k5556556',
    'k5565566',
    'k55k5566',
    'k5k.k556',
    '.k...k56',
    '......k5',
    '.......k'] });
  A.add('enemies', 'acolyte', { name: 'Acolyte', variants: { 'Red acolyte': { p: 'R', v: 'k' } }, half: [
    '......kk',
    '.....kpp',
    '....kppp',
    '...kpppp',
    '...kppkk',
    '...kpkSS',
    '...kpkkS',
    '...kpkSS',
    '..kppkkk',
    '.kpppppy',
    '.kppvppB',
    'kpppvpSB',
    'kpppvppp',
    'kppvvppp',
    '.kpvvppp',
    '.kkkkkkk'] });
  A.add('enemies', 'warder', { name: 'Warder', variants: { 'Gilt warder': { m: 'g', M: 'G', i: 'w', t: 'R', T: 'e', g: '#' } }, half: [
    '.....kee',
    '....kkee',
    '...kmmmm',
    '..kmMMmm',
    '..kmkkkk',
    '..kmmkmk',
    '..kimmmm',
    '...kkiii',
    '.kkmmkkk',
    'kmMmkttt',
    'kmmmkttT',
    'kiimktTg',
    '.kkikttg',
    '..kikktt',
    '..kiikkt',
    '..kkkk.k'] });
  A.add('enemies', 'watcher', { name: 'Watcher', variants: { 'Bloodshot': { t: 'R', T: 'e' } }, half: [
    '........',
    '........',
    '.....kkk',
    '...kkBBB',
    '..kBeBBB',
    '.kBBBBtt',
    '.kBBBtTT',
    'kBBBBtTk',
    'kBBBBtTk',
    '.kBBBtTT',
    '.kbBBBtt',
    '..kbBeBB',
    '...kkbbb',
    '.....kkk',
    '........',
    '........'] });
  A.add('enemies', 'mimic', { name: 'Mimic', variants: { 'Iron mimic': { W: 'm', w: 'i', l: 'M' } }, half: [
    '........',
    '........',
    '........',
    '..kkkkkk',
    '.kWWWWWW',
    'kWlWyWWg',
    'kWWWWWWg',
    'kkkkkkkk',
    'k#k#k#k#',
    'kReeeeee',
    'k#k#keee',
    'kkkkkkee',
    'kwWWWWkk',
    'kwWWWWWW',
    'kkkkkkkk',
    '........'] });

  /* ---------- bosses ---------- */
  A.add('bosses', 'turnkey', { name: 'The Turnkey', slice: true, half: [
    '................',
    '..k.............',
    '..kk.........kkk',
    '..kik......kkgGg',
    '..kiik....kgGGGg',
    '...kiik..kkgGgGG',
    '...kimikkkiiiiii',
    '....kimmiimmmmmm',
    '....kkimmmmMMmmm',
    '.....kimmmmmmmmm',
    '.....kimkkkkkkkk',
    '.....kimkkReyY##',
    '.....kimkkkkkkkk',
    '.....kiimmmkmkmk',
    '....kkkiimmkmkmk',
    '..kkiiikkiiiiiii',
    '.kiimmmiikkkkkkk',
    'kiimMMmmiikRRRRR',
    'kimMMMmmmikRRRRR',
    'kimmMmmmmikRRgRR',
    'kiimmmmmiikRgRgR',
    '.kiimmmiikRRgRRg',
    '.kkiiiiikRRRRggG',
    '.kSSkkkkRRRRRRgG',
    '.kSSkkRRRRRRRRgG',
    '..kk.kRRRRRRRRgG',
    '.....kRRReRRRRgg',
    '.....kRReRRRRRRR',
    '....kRRReRRRRRRR',
    '....kRReRRRReRRR',
    '....kkRRkkRRkkRR',
    '.....kkk.kkk.kkk'] });
  A.add('bosses', 'warden', { name: 'The Warden', half: [
    '................',
    '..............kk',
    '.............kee',
    '............keee',
    '..........kkkeee',
    '.........kmmmmee',
    '........kmMMmmmm',
    '........kmMmmmmm',
    '........kmmkkkkk',
    '........kmmkTTkk',
    '........kmmkkkkk',
    '........kimmmkmk',
    '.........kimmkmk',
    '....kkkkkkkiimmm',
    '..kkmmmmmkkkiiii',
    '.kmmMMMmmmmkkkkk',
    'kmmMMmmmmmmkgggM',
    'kmmmmmmmmmikkkgM',
    'kiimmmmmmiikttkM',
    '.kiiiiiiikkttttM',
    '.kSSkkkkkktttTkM',
    '.kSSk..ktttttTkM',
    '..kk...kttttttkM',
    '.......kttttttkM',
    '......kttttTttkM',
    '......kttttTttkM',
    '......ktttttttkM',
    '.....kttdttttdkM',
    '.....ktdtttdttkM',
    '.....kkdkktdkkkM',
    '......kkiikkiikm',
    '......kkkkkkkkkk'] });
  A.add('bosses', 'abbot', { name: 'The Drowned Abbot', half: [
    '..............kk',
    '.............kGG',
    '............kGgG',
    '...........kGGgG',
    '...........kGggG',
    '..........kGGgee',
    '..........kGGggG',
    '.........kkkkkkk',
    '.........ktttttt',
    '........kttTTTTT',
    '........ktkkktTT',
    '........ktk#ktTT',
    '........kttttttk',
    '.........kttkkkk',
    '.........kdtk#k#',
    '......kkkkddtttt',
    '....kkppppkdddtt',
    '...kpppPpppkkkkk',
    '..kppPPppppppGgG',
    '..kpppppppppkgGg',
    '.kpppppvppkkkGgG',
    '.kppppvvpkttkgGg',
    'kppppvvppktttkyG',
    'kpppvvpppkkkkoyY',
    'kpppvppppppkkroy',
    'kppvvpppppvpkkkk',
    'kppvpppppvvppGgG',
    '.kpvpppppvppkgGg',
    '.kpppdpppvppkGgG',
    '.kkpddppkkppkgGg',
    '..kkdkkkkdkkkkkk',
    '...k.k..k.k.....'] });
  A.add('bosses', 'saint', { name: 'The Ossuary Saint', half: [
    '..............yy',
    '....y.........YY',
    '....Y....y....BB',
    '....B....Y....BB',
    '....B..kkBkkkkBB',
    '....BkkBBBBBBBBB',
    '...kkBBBBBBBBBBB',
    '..kBBBBBBBBBBBBB',
    '.kBBBBBBBBBBBBBB',
    '.kBBBBBBBBBBBBBB',
    'kBBBbBBBBBBBBBBB',
    'kBBbBBkkkkkkBBBB',
    'kBBbBkkkkkkkkBBB',
    'kBBBkkkkeekkkkBB',
    'kBBBkkkeYYekkkBB',
    'kBBBkkkkeekkkkBB',
    'kbBBBkkkkkkkkBBk',
    '.kBBBBkkkkkkBBkk',
    '.kbBBBBBBBBBBBkk',
    '..kbBBBBBBBBBkkk',
    '..kbbBBBBBBBBBkk',
    '...kbBBBBBBBBBBB',
    '...kbBkBBkBBkBBk',
    '...kbBkBBkBBkBBk',
    '...kkkkkkkkkkkkk',
    '....kbkBBkBBkBBk',
    '....kbkBBkBBkBBk',
    '....kbbBBBBBBBBB',
    '.....kbbBBBBBBBB',
    '......kkbbbBBBBB',
    '........kkkbbbbb',
    '...........kkkkk'] });
  A.add('bosses', 'redcap', { name: 'Mother Redcap', half: [
    '................',
    '..........kkkkkk',
    '.......kkkeeeeee',
    '.....kkeeeeeee##',
    '....keeee##eeee#',
    '...keeee####eeee',
    '..keeeee####eeee',
    '.keeeeeee##eeeee',
    '.kee##eeeeeeeeee',
    'kee####eeeeeee##',
    'kee####eeeeee###',
    'keee##eeeeeeee##',
    'kReeeeeeeeeeeeee',
    'kRReeeeeeeeeeeee',
    '.kRRRReeeeeeeeee',
    '..kkkRRRRRRRRRRR',
    '.....kkkkknnnnnn',
    '........kbbbbbbb',
    '.......kbbbBBBBB',
    '.......kbbkkkBBB',
    '.......kbbkykBBB',
    '.......kbbkkkBBB',
    '......kbbbBBBBBk',
    '....kkkbbbBkkkkk',
    '..kkhhkbbbk#k#k#',
    '.khhhkkbbbBkkkkk',
    'khhkk.kbbbBBBBBB',
    'khk...kbbbbBBBBB',
    '.k...kbbnbbbBBBB',
    '....kbbnnbbnbbBB',
    '...kbnkkbnkkbnkk',
    '...kkk..kk..kk..'] });
})(typeof module !== 'undefined' && module.exports ? require('./bank.js') : OUB_ART);
